#define White_Knight 'N'
#define White_King 'K'
#define White_Queen 'Q'
#define White_Rook 'R'
#define White_Bishop 'B'
#define White_Pawn 'P'
#define Black_Knight 'n'
#define Black_King 'k'
#define Black_Queen 'q'
#define Black_Rook 'r'
#define Black_Bishop 'b'
#define Black_Pawn 'p'

